name: senio_care
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1

  device_preview: ^1.3.1
  google_fonts: ^6.3.1
  lottie: ^3.3.1

  injectable: ^2.5.0
  get_it: ^7.7.0

  # ===== NETWORK (STABLE) =====
  dio: 5.4.3
  retrofit: 4.7.2
  retrofit_generator: 8.1.0
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: 4.0.3

  json_annotation: ^4.9.0

  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2

  provider: ^6.1.2

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  cloud_firestore: ^6.0.3
  google_sign_in: ^6.2.1
  easy_localization:
  loading_animation_widget: ^1.3.0
  internet_connection_checker: ^1.0.0
  percent_indicator: ^4.2.5
  dropdown_search: ^6.0.2
  font_awesome_flutter: ^10.12.0
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  injectable_generator: ^2.5.0

dependency_overrides:
  dio: 5.4.3

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/json/

  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth/Amaranth-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amaranth/Amaranth-Regular.ttf
          weight: 400
