sonar.projectKey=graduation-project-SenioCare-2026_senio_care
sonar.organization=graduation-project-seniocare-2026
sonar.host.url=https://sonarcloud.io

sonar.projectName=senio_care
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/build/**,**/ios/**,**/android/**,**/web/**,**/macos/**,lib/**/*.g.dart,**/mock/**,**/*mock*.*
sonar.sourceEncoding=UTF-8
